'use client';

import { useState, useEffect, useRef } from 'react';
import { useSearchParams } from 'next/navigation';
import {
    Sparkles, Send, Play, FileText, CheckCircle, Clock,
    Briefcase, Zap, MessageSquare, LifeBuoy, AlertCircle, File,
    BookOpen
} from 'lucide-react';

// --- TYPES ---
type AgentType = 'business' | 'automation' | 'content' | 'support';

interface Action {
    label: string;
    intent: string;
    primary?: boolean;
    status?: 'idle' | 'executing' | 'done' | 'failed';
}

interface TaskOutput {
    summary: string;
    steps?: string[];
    content?: string;
    files?: { name: string; type: string }[];
    actions: Action[];
}

interface Task {
    id: number;
    query: string;
    agent: AgentType;
    status: 'processing' | 'completed' | 'error';
    output?: TaskOutput;
    timestamp: number;
}

// --- AGENT CONFIGURATION ---
const AGENTS: Record<string, { name: string; role: string; icon: any; color: string }> = {
    business: { name: 'Business Assistant', role: 'Strategy & Ops', icon: Briefcase, color: '#00e0ff' },
    automation: { name: 'Automation Agent', role: 'Workflow Automator', icon: Zap, color: '#f59e0b' },
    content: { name: 'Content Creator', role: 'Social & Copy', icon: MessageSquare, color: '#10b981' },
    support: { name: 'Support Agent', role: 'Customer Success', icon: LifeBuoy, color: '#ec4899' },
};

export default function AgentsPage() {
    const searchParams = useSearchParams();
    const activeAgentType = (searchParams.get('type') as AgentType) || 'business';
    const activeAgent = AGENTS[activeAgentType] || AGENTS.business;

    const [command, setCommand] = useState('');
    const [isProcessing, setIsProcessing] = useState(false);
    const [tasks, setTasks] = useState<Task[]>([]);
    const [suggestionsVisible, setSuggestionsVisible] = useState(true);
    const [showProactiveToast, setShowProactiveToast] = useState(false);

    // --- PROACTIVE LOGIC ---
    useEffect(() => {
        const timer = setInterval(() => {
            if (tasks.length > 0 && !isProcessing) {
                setShowProactiveToast(true);
                setTimeout(() => setShowProactiveToast(false), 5000); // Auto hide
            }
        }, 45000); // Check every 45s
        return () => clearInterval(timer);
    }, [tasks.length, isProcessing]);

    // --- COMMAND EXECUTION ---
    const handleExecute = async () => {
        if (!command.trim()) return;

        setIsProcessing(true);
        setSuggestionsVisible(false);
        setShowProactiveToast(false);

        const tempId = Date.now();
        const currentCommand = command; // Capture for async usage

        // 1. Optimistic Update (Show user query immediately)
        setTasks(prev => [{
            id: tempId,
            query: currentCommand,
            agent: activeAgentType,
            status: 'processing',
            timestamp: Date.now()
        }, ...prev]);

        setCommand('');

        // 2. Logic Router
        try {
            let output: TaskOutput;

            // --- REAL API CALL (Business Agent) ---
            if (activeAgentType === 'business') {
                console.log('Sending request to Gemini API via /api/advice...', { currentCommand });

                const res = await fetch('/api/advice', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        business: "General Business Context", // In real app, load from user profile
                        problem: currentCommand,
                        goal: "Provide strategic advice and actionable steps"
                    })
                });

                if (!res.ok) {
                    const errorText = await res.text();
                    console.error('API Error:', res.status, errorText);
                    throw new Error(`API Connection Failed: ${res.status}`);
                }

                const data = await res.json();

                // Construct output from Real AI Response
                output = {
                    summary: "Strategy generated by AI Model (Gemini 1.5 Flash).",
                    steps: ["Processed business context", "Analyzed problem statement", "Generated strategic advice"],
                    content: data.advice,
                    actions: [
                        { label: "Save to Notes", intent: "save_notes", primary: true },
                        { label: "Share with Team", intent: "share_team" },
                        { label: "Refine Strategy", intent: "refine" }
                    ]
                };

            } else {
                // --- MOCK RESPONSE (Other Agents) ---
                console.log('Using Mock Agent for:', activeAgentType);
                await new Promise(resolve => setTimeout(resolve, 2000));
                output = generateMockResponse(activeAgentType, currentCommand);
            }

            // 3. Update Task with Success
            setTasks(prev => prev.map(t => {
                if (t.id === tempId) {
                    return { ...t, status: 'completed', output };
                }
                return t;
            }));

        } catch (error) {
            console.error("Agent Execution Error:", error);
            // Error State Update
            setTasks(prev => prev.map(t => {
                if (t.id === tempId) {
                    return {
                        ...t,
                        status: 'error',
                        output: {
                            summary: "System Error: Could not connect to AI Neural Core.",
                            content: "Please check your internet connection or verify API keys. Check console for details.",
                            actions: [{ label: "Retry", intent: "retry", primary: true }]
                        }
                    };
                }
                return t;
            }));
        } finally {
            setIsProcessing(false);
        }
    };

    const handleActionClick = (taskId: number, actionIndex: number) => {
        // Prevent auto-execution logic here. 
        setTasks(prev => prev.map(t => {
            if (t.id === taskId && t.output) {
                const newActions = [...t.output.actions];
                newActions[actionIndex] = { ...newActions[actionIndex], status: 'done', label: 'Completed' };
                return { ...t, output: { ...t.output, actions: newActions } };
            }
            return t;
        }));
    };

    return (
        <div className="flex-1 flex overflow-hidden bg-[#0B1120] text-gray-100 font-sans selection:bg-[#00e0ff] selection:text-black">

            {/* --- MAIN PANEL --- */}
            <div className="flex-1 flex flex-col relative w-full max-w-5xl mx-auto">

                {/* Header */}
                <header className="h-16 flex items-center justify-between px-6 lg:px-8 border-b border-white/5 bg-[#0F172A]/80 backdrop-blur-md z-10 transition-colors duration-500" style={{ borderColor: `${activeAgent.color}20` }}>
                    <div className="flex items-center gap-3">
                        <div className="p-1.5 rounded-lg border bg-opacity-10 backdrop-blur-md"
                            style={{ backgroundColor: `${activeAgent.color}10`, borderColor: `${activeAgent.color}30` }}>
                            <activeAgent.icon className="w-4 h-4" style={{ color: activeAgent.color }} />
                        </div>
                        <div>
                            <h2 className="text-sm font-bold text-white tracking-wide">{activeAgent.name}</h2>
                            <div className="flex items-center gap-2">
                                <span className="w-1.5 h-1.5 rounded-full bg-green-500 shadow-[0_0_8px_#22c55e]" />
                                <span className="text-[10px] uppercase tracking-wider text-green-500 font-medium">Online (v2.2 Connected)</span>
                            </div>
                        </div>
                    </div>
                </header>

                {/* Scrollable Feed */}
                <div className="flex-1 overflow-y-auto px-6 lg:px-8 py-8 space-y-8 scroll-smooth min-h-0">

                    {/* Empty State */}
                    {tasks.length === 0 && !isProcessing && (
                        <div className="h-full flex flex-col items-center justify-center text-center opacity-0 animate-in fade-in zoom-in duration-500 pb-20">
                            <div className="relative mb-8 group">
                                <div className="absolute inset-0 blur-[60px] opacity-20 rounded-full transition-colors duration-700" style={{ backgroundColor: activeAgent.color }} />
                                <div className="relative w-24 h-24 rounded-2xl bg-gradient-to-tr from-[#0F172A] to-[#1E293B] border border-white/10 flex items-center justify-center shadow-2xl ring-1 ring-white/5 group-hover:scale-105 transition-transform duration-500">
                                    <activeAgent.icon className="w-10 h-10 text-white" />
                                </div>
                            </div>
                            <h1 className="text-3xl lg:text-4xl font-bold text-white mb-3">
                                {activeAgent.name} System
                            </h1>
                            <p className="text-gray-400 max-w-md text-lg leading-relaxed">
                                Ready to assist. Select an action or describe your objective to begin.
                            </p>
                        </div>
                    )}

                    {/* Task History */}
                    {tasks.slice().reverse().map((task) => (
                        <div key={task.id} className="w-full max-w-3xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500">

                            {/* User Query Block */}
                            <div className="flex justify-end mb-4 group">
                                <div className="bg-[#1E293B] pl-5 pr-5 py-3.5 rounded-2xl rounded-tr-sm text-gray-200 border border-white/5 shadow-md max-w-xl text-[15px] leading-relaxed relative overflow-hidden">
                                    {task.query}
                                </div>
                            </div>

                            {/* Agent Output Block */}
                            <div className="flex gap-4">
                                <div className="w-8 h-8 rounded-full flex items-center justify-center shrink-0 shadow-lg mt-1"
                                    style={{ background: `linear-gradient(135deg, ${AGENTS[task.agent].color}, #3b82f6)` }}>
                                    <Sparkles className="w-4 h-4 text-white" />
                                </div>

                                <div className="flex-1 space-y-3">
                                    {task.status === 'processing' ? (
                                        <div className="flex items-center gap-3 text-sm h-10 px-4" style={{ color: AGENTS[task.agent].color }}>
                                            <span className="relative flex h-2.5 w-2.5">
                                                <span className="animate-ping absolute inline-flex h-full w-full rounded-full opacity-75" style={{ backgroundColor: AGENTS[task.agent].color }}></span>
                                                <span className="relative inline-flex rounded-full h-2.5 w-2.5" style={{ backgroundColor: AGENTS[task.agent].color }}></span>
                                            </span>
                                            Processing request via Neural Core...
                                        </div>
                                    ) : task.status === 'error' ? (
                                        <div className="bg-red-900/10 border border-red-500/20 p-4 rounded-xl text-red-400 text-sm">
                                            <p className="font-bold flex items-center gap-2"><AlertCircle className="w-4 h-4" /> Execution Failed</p>
                                            <p className="mt-1 opacity-80">{task.output?.summary}</p>
                                            <p className="mt-1 opacity-60 text-xs">{task.output?.content}</p>
                                        </div>
                                    ) : (
                                        <div className="bg-[#0F172A] border border-white/10 rounded-xl overflow-hidden shadow-2xl ring-1 ring-white/5">
                                            {/* Summary Header */}
                                            <div className="px-5 py-4 border-b border-white/5 bg-white/[0.02]">
                                                <h3 className="font-semibold text-white text-[15px] mb-1">Execution Complete</h3>
                                                <p className="text-sm text-gray-400">{task.output?.summary}</p>
                                            </div>

                                            {/* Structured Content */}
                                            <div className="p-5 space-y-4">
                                                {/* Steps List */}
                                                {task.output?.steps && (
                                                    <div className="space-y-2">
                                                        {task.output.steps.map((step, idx) => (
                                                            <div key={idx} className="flex gap-3 text-sm text-gray-300">
                                                                <CheckCircle className="w-4 h-4 text-green-500 shrink-0 mt-0.5" />
                                                                <span>{step}</span>
                                                            </div>
                                                        ))}
                                                    </div>
                                                )}

                                                {/* Text Content / Artifact */}
                                                {task.output?.content && (
                                                    <div className="bg-black/30 rounded-lg p-4 font-mono text-xs text-gray-300 border border-white/5 leading-relaxed whitespace-pre-wrap">
                                                        {task.output.content}
                                                    </div>
                                                )}

                                                {/* Files */}
                                                {task.output?.files && (
                                                    <div className="flex gap-2 flex-wrap">
                                                        {task.output.files.map((f, i) => (
                                                            <div key={i} className="flex items-center gap-2 px-3 py-2 bg-[#1E293B] rounded border border-white/10 text-xs text-gray-300">
                                                                <File className="w-3 h-3 text-[#00e0ff]" />
                                                                {f.name}
                                                            </div>
                                                        ))}
                                                    </div>
                                                )}
                                            </div>

                                            {/* Action Bar */}
                                            <div className="px-5 py-4 bg-[#0B1120] border-t border-white/5 flex flex-wrap gap-2 justify-end">
                                                {task.output?.actions.map((action, idx) => (
                                                    <button
                                                        key={idx}
                                                        onClick={() => handleActionClick(task.id, idx)}
                                                        disabled={action.status === 'done'}
                                                        className={`px-4 py-2 rounded-lg text-xs font-semibold tracking-wide transition-all flex items-center gap-2 ${action.status === 'done'
                                                            ? 'bg-green-500/10 text-green-500 border border-green-500/20 cursor-default'
                                                            : action.primary
                                                                ? 'bg-[#00e0ff] text-black hover:bg-[#00e0ff]/90 hover:scale-[1.02] hover:shadow-[0_0_12px_#00e0ff50]'
                                                                : 'bg-white/5 text-gray-300 border border-white/10 hover:bg-white/10 hover:text-white'
                                                            }`}
                                                    >
                                                        {action.status === 'done' && <CheckCircle className="w-3 h-3" />}
                                                        {action.label}
                                                    </button>
                                                ))}
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>
                    ))}

                    <div className="pb-32" />
                </div>

                {/* --- INPUT AREA --- */}
                <div className="absolute bottom-0 left-0 right-0 p-6 lg:p-10 bg-gradient-to-t from-[#0B1120] via-[#0B1120] to-transparent z-20">

                    {/* Contextual Suggestions */}
                    {suggestionsVisible && !isProcessing && (
                        <div className="flex justify-center flex-wrap gap-3 mb-6 max-w-4xl mx-auto opacity-0 animate-in slide-in-from-bottom-2 duration-700 delay-200 fade-in-0 fill-mode-forwards">
                            {getSuggestions(activeAgentType).map((bg, idx) => (
                                <SuggestionChip
                                    key={idx}
                                    icon={bg.icon}
                                    label={bg.label}
                                    onClick={() => setCommand(bg.prompt)}
                                />
                            ))}
                        </div>
                    )}

                    {/* Proactive Toast */}
                    {showProactiveToast && (
                        <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-full mb-4 bg-[#1E293B] border border-[#00e0ff]/30 text-gray-200 px-4 py-3 rounded-xl shadow-2xl flex items-center gap-3 animate-in fade-in slide-in-from-bottom-2 z-50">
                            <Sparkles className="w-4 h-4 text-[#00e0ff] animate-pulse" />
                            <span className="text-sm">Suggestion: Review the Q3 performance report?</span>
                            <button className="text-xs bg-[#00e0ff]/10 text-[#00e0ff] px-2 py-1 rounded hover:bg-[#00e0ff]/20">Review</button>
                            <button onClick={() => setShowProactiveToast(false)} className="ml-2 text-gray-500 hover:text-white">&times;</button>
                        </div>
                    )}

                    {/* Main Input Field */}
                    <div className="max-w-3xl mx-auto relative group">
                        <div
                            className="absolute -inset-[1px] rounded-2xl opacity-0 group-focus-within:opacity-100 transition-opacity duration-500 blur-sm"
                            style={{ background: `linear-gradient(to right, ${activeAgent.color}, #a855f7, ${activeAgent.color})` }}
                        />
                        <div className="relative flex items-center bg-[#0F172A] rounded-xl border border-white/10 shadow-2xl overflow-hidden">
                            <textarea
                                value={command}
                                onChange={(e) => setCommand(e.target.value)}
                                onKeyDown={(e) => e.key === 'Enter' && !e.shiftKey && (e.preventDefault(), handleExecute())}
                                placeholder={`What should the ${activeAgent.name} accomplish?`}
                                disabled={isProcessing}
                                className="w-full bg-transparent border-none focus:ring-0 text-white placeholder:text-gray-500 px-5 py-4 min-h-[60px] max-h-[120px] resize-none text-[15px]"
                                rows={1}
                            />
                            <div className="pr-2">
                                <button
                                    onClick={handleExecute}
                                    disabled={!command.trim() || isProcessing}
                                    className="p-3 text-black rounded-lg transition-all hover:scale-105 disabled:opacity-30 disabled:cursor-not-allowed disabled:shadow-none"
                                    style={{ backgroundColor: activeAgent.color, boxShadow: !isProcessing && command.trim() ? `0 0 20px ${activeAgent.color}40` : 'none' }}
                                >
                                    <Send className="w-5 h-5" />
                                </button>
                            </div>
                        </div>
                    </div>
                    <p className="text-center text-[11px] text-gray-600 mt-4 uppercase tracking-widest font-medium">
                        Enterprise AI Orchestrator v2.2 • Active Module: {activeAgent.name}
                    </p>
                </div>

            </div>

            {/* --- RIGHT SIDEBAR (Context) --- */}
            <div className="w-80 border-l border-white/5 bg-[#0F172A]/50 backdrop-blur-sm hidden 2xl:block p-6">
                <div className="mb-8">
                    <h3 className="text-xs font-bold text-gray-500 uppercase tracking-widest mb-4">System Status</h3>
                    <div className="space-y-3">
                        <div className="p-3 bg-white/5 rounded-lg border border-white/5 flex items-center justify-between">
                            <span className="text-sm text-gray-400">Memory Usage</span>
                            <span className="text-xs font-mono text-[#00e0ff]">12%</span>
                        </div>
                        <div className="p-3 bg-white/5 rounded-lg border border-white/5 flex items-center justify-between">
                            <span className="text-sm text-gray-400">Context Window</span>
                            <span className="text-xs font-mono text-green-500">4k / 128k</span>
                        </div>
                    </div>
                </div>

                <div>
                    <h3 className="text-xs font-bold text-gray-500 uppercase tracking-widest mb-4">Pending Approvals</h3>
                    <div className="p-4 rounded-xl border border-yellow-500/20 bg-yellow-500/5">
                        <div className="flex items-start gap-3">
                            <AlertCircle className="w-4 h-4 text-yellow-500 shrink-0 mt-0.5" />
                            <div>
                                <p className="text-sm text-yellow-200 font-medium mb-1">Stripe Payout</p>
                                <p className="text-xs text-yellow-500/80 mb-3">Requires manual confirmation.</p>
                                <button className="text-xs bg-yellow-500/20 text-yellow-500 px-3 py-1.5 rounded items-center hover:bg-yellow-500/30 transition">Review</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    );
}

// --- HELPERS ---

function SuggestionChip({ icon, label, onClick }: any) {
    return (
        <button
            onClick={onClick}
            className="flex items-center gap-2.5 px-5 py-3 rounded-full bg-[#1E293B] border border-white/10 hover:border-[#00e0ff]/50 hover:bg-[#1E293B]/80 text-sm font-medium text-gray-300 hover:text-white transition-all shadow-lg hover:shadow-[#00e0ff]/10 hover:-translate-y-0.5"
        >
            <span className="text-[#00e0ff]">{icon}</span>
            {label}
        </button>
    )
}

function getSuggestions(type: AgentType) {
    switch (type) {
        case 'content':
            return [
                { icon: <MessageSquare className="w-4 h-4" />, label: "Draft LinkedIn Post", prompt: "Draft a viral LinkedIn post about AI agents" },
                { icon: <Play className="w-4 h-4" />, label: "Video Script", prompt: "Create a 60s video script for product launch" },
                { icon: <FileText className="w-4 h-4" />, label: "Newsletter Outline", prompt: "Generate outline for weekly newsletter" },
            ];
        case 'support':
            return [
                { icon: <CheckCircle className="w-4 h-4" />, label: "Resolve Ticket #429", prompt: "Suggest resolution for ticket #429 (Billing Issue)" },
                { icon: <BookOpen className="w-4 h-4" />, label: "Update FAQ", prompt: "Draft new FAQ entry for 'Refund Policy'" },
            ];
        case 'automation':
            return [
                { icon: <Zap className="w-4 h-4" />, label: "Optimize Workflow", prompt: "Analyze the 'Lead Intake' workflow for bottlenecks" },
                { icon: <Clock className="w-4 h-4" />, label: "Daily Summary", prompt: "Run daily automation summary report" },
            ];
        default: // Business
            return [
                { icon: <FileText className="w-4 h-4" />, label: "Proposal Draft", prompt: "Draft a proposal for client Acme Corp" },
                { icon: <Briefcase className="w-4 h-4" />, label: "Market Analysis", prompt: "Analyze competitors in AI space" },
                { icon: <Clock className="w-4 h-4" />, label: "Schedule Meeting", prompt: "Find time for team sync next week" },
            ];
    }
}

function generateMockResponse(type: AgentType, query: string): TaskOutput {
    // Simulated Responses based on Agent Persona
    if (type === 'content') {
        return {
            summary: "I've drafted 3 content variations based on your request.",
            steps: ["Analyzed trending topics", "Drafted 3 hooks", "Generated body copy"],
            content: "Option 1 (Viral):\nSecret to scaling? Automation.\n\nOption 2 (Educational):\nHere is how AI is changing workforce dynamics...",
            actions: [
                { label: "Post to LinkedIn", intent: "post_linkedin", primary: true },
                { label: "Save to Notion", intent: "save_notion" }
            ]
        }
    }
    if (type === 'support') {
        return {
            summary: "Analyzed ticket history and drafted a response.",
            steps: ["Retrieved user context", "Checked billing status", "Drafted refund confirmation"],
            content: "Hi [User],\n\nI've confirmed the double charge. I have processed the refund of $49...",
            actions: [
                { label: "Send Reply", intent: "send_reply", primary: true },
                { label: "Escalate to Human", intent: "escalate" }
            ]
        }
    }
    // Default Business Mock (ONLY used if API logic checks fail or for non-Business types hitting default)
    return {
        summary: "Proposal outline generated successfully (Mock).",
        steps: ["Researched client background", "Outlined key deliverables", "Estimated timeline"],
        content: "# Proposal for [Client]\n\n## Executive Summary\nImplementing autonomous agents will reduce overhead by 40%.\n\n## Timeline\nPhase 1: Deep Dive...",
        files: [{ name: "proposal_draft_v1.pdf", type: "pdf" }],
        actions: [
            { label: "Send via Email", intent: "email_proposal", primary: true },
            { label: "Export as PDF", intent: "export_pdf" }
        ]
    }
}
